// generated by src/lib/highlight_priorities.gen.ts - DO NOT EDIT OR RISK LOST DATA

export type Highlight_Token_Name =
	| 'namespace'
	| 'tag'
	| 'constant'
	| 'symbol'
	| 'deleted'
	| 'keyword'
	| 'null'
	| 'boolean'
	| 'interpolation_punctuation'
	| 'special_keyword'
	| 'comment'
	| 'char'
	| 'builtin'
	| 'inserted'
	| 'class_name'
	| 'number'
	| 'attr_value'
	| 'attr_quote'
	| 'string'
	| 'template_punctuation'
	| 'selector'
	| 'function'
	| 'regex'
	| 'important'
	| 'variable'
	| 'atrule'
	| 'rule'
	| 'attr_name'
	| 'property'
	| 'decorator'
	| 'decorator_name'
	| 'bold'
	| 'italic'
	| 'attr_equals'
	| 'processing_instruction'
	| 'doctype'
	| 'cdata'
	| 'punctuation';

export const highlight_priorities: Record<Highlight_Token_Name, number> = {
	namespace: 1,
	tag: 2,
	constant: 2,
	symbol: 2,
	deleted: 2,
	keyword: 3,
	null: 3,
	boolean: 3,
	interpolation_punctuation: 3,
	special_keyword: 4,
	comment: 5,
	char: 5,
	builtin: 5,
	inserted: 5,
	class_name: 6,
	number: 6,
	attr_value: 7,
	attr_quote: 7,
	string: 7,
	template_punctuation: 7,
	selector: 8,
	function: 8,
	regex: 8,
	important: 8,
	variable: 8,
	atrule: 9,
	rule: 10,
	attr_name: 11,
	property: 11,
	decorator: 11,
	decorator_name: 11,
	bold: 12,
	italic: 13,
	attr_equals: 14,
	processing_instruction: 14,
	doctype: 14,
	cdata: 14,
	punctuation: 14,
} as const;

// generated by src/lib/highlight_priorities.gen.ts - DO NOT EDIT OR RISK LOST DATA
