// generated by src/lib/highlight_priorities.gen.ts - DO NOT EDIT OR RISK LOST DATA

export type Highlight_Token_Name =
	| 'tag'
	| 'constant'
	| 'symbol'
	| 'deleted'
	| 'keyword'
	| 'null'
	| 'boolean'
	| 'interpolation_punctuation'
	| 'comment'
	| 'char'
	| 'builtin'
	| 'inserted'
	| 'class_name'
	| 'number'
	| 'attr_value'
	| 'attr_quote'
	| 'string'
	| 'template_punctuation'
	| 'selector'
	| 'function'
	| 'regex'
	| 'important'
	| 'variable'
	| 'atrule'
	| 'rule'
	| 'attr_name'
	| 'property'
	| 'decorator'
	| 'decorator_name'
	| 'special_keyword'
	| 'namespace'
	| 'at_keyword'
	| 'attr_equals'
	| 'processing_instruction'
	| 'doctype'
	| 'cdata'
	| 'punctuation'
	| 'bold'
	| 'italic';

export const highlight_priorities: Record<Highlight_Token_Name, number | undefined> = {
	tag: 1,
	constant: 1,
	symbol: 1,
	deleted: 1,
	keyword: 2,
	null: 2,
	boolean: 2,
	interpolation_punctuation: 2,
	comment: 3,
	char: 3,
	builtin: 3,
	inserted: 3,
	class_name: 4,
	number: 4,
	attr_value: 5,
	attr_quote: 5,
	string: 5,
	template_punctuation: 5,
	selector: 6,
	function: 6,
	regex: 6,
	important: 6,
	variable: 6,
	atrule: 7,
	rule: 8,
	attr_name: 9,
	property: 9,
	decorator: 9,
	decorator_name: 9,
	special_keyword: 10,
	namespace: 10,
	at_keyword: 11,
	attr_equals: 12,
	processing_instruction: 12,
	doctype: 12,
	cdata: 12,
	punctuation: 12,
	bold: 13,
	italic: 14,
} as const;

// generated by src/lib/highlight_priorities.gen.ts - DO NOT EDIT OR RISK LOST DATA
