// generated by src/lib/highlight_priorities.gen.ts - DO NOT EDIT OR RISK LOST DATA

export type Highlight_Token_Name =
	| 'tag'
	| 'constant'
	| 'symbol'
	| 'deleted'
	| 'keyword'
	| 'null'
	| 'boolean'
	| 'interpolation_punctuation'
	| 'comment'
	| 'char'
	| 'builtin'
	| 'inserted'
	| 'class_name'
	| 'number'
	| 'attr_value'
	| 'attr_quote'
	| 'string'
	| 'template_punctuation'
	| 'selector'
	| 'function'
	| 'regex'
	| 'important'
	| 'variable'
	| 'atrule'
	| 'attr_name'
	| 'property'
	| 'decorator'
	| 'decorator_name'
	| 'special_keyword'
	| 'namespace'
	| 'rule'
	| 'at_keyword'
	| 'attr_equals'
	| 'processing_instruction'
	| 'doctype'
	| 'cdata'
	| 'punctuation'
	| 'bold'
	| 'italic';

export const highlight_priorities: Record<Highlight_Token_Name, number | undefined> = {
	tag: 1,
	constant: 1,
	symbol: 1,
	deleted: 1,
	keyword: 1,
	null: 1,
	boolean: 1,
	interpolation_punctuation: 1,
	comment: 2,
	char: 2,
	builtin: 2,
	inserted: 2,
	class_name: 3,
	number: 3,
	attr_value: 4,
	attr_quote: 4,
	string: 4,
	template_punctuation: 4,
	selector: 5,
	function: 5,
	regex: 5,
	important: 5,
	variable: 5,
	atrule: 6,
	attr_name: 7,
	property: 7,
	decorator: 7,
	decorator_name: 7,
	special_keyword: 8,
	namespace: 8,
	rule: 8,
	at_keyword: 9,
	attr_equals: 10,
	processing_instruction: 10,
	doctype: 10,
	cdata: 10,
	punctuation: 10,
	bold: 11,
	italic: 12,
} as const;

// generated by src/lib/highlight_priorities.gen.ts - DO NOT EDIT OR RISK LOST DATA
