// generated by src/routes/package.gen.ts

import type {Package_Json} from '@ryanatkn/belt/package_json.js';
import type {Src_Json} from '@ryanatkn/belt/src_json.js';

export const package_json: Package_Json = {
	name: '@ryanatkn/fuz_code',
	version: '0.29.0',
	description: 'syntax styling utilities and components for TypeScript, Svelte, and Markdown',
	glyph: '🎨',
	logo: 'logo.svg',
	logo_alt: 'a friendly pink spider facing you',
	public: true,
	license: 'MIT',
	homepage: 'https://code.fuz.dev/',
	repository: 'https://github.com/ryanatkn/fuz_code',
	author: {name: 'Ryan Atkinson', email: 'mail@ryanatkn.com', url: 'https://www.ryanatkn.com/'},
	bugs: 'https://github.com/ryanatkn/fuz_code/issues',
	funding: 'https://www.ryanatkn.com/funding',
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		check: 'gro check',
		test: 'gro test',
		preview: 'vite preview',
		deploy: 'gro deploy',
		benchmark: 'gro run benchmark/run_benchmarks.ts',
		'benchmark-compare': 'gro run benchmark/compare/run_compare.ts',
		'update-generated-fixtures': 'gro src/fixtures/update',
	},
	type: 'module',
	engines: {node: '>=22.15'},
	peerDependencies: {'@ryanatkn/belt': '^0.35.1', '@ryanatkn/moss': '^0.36.2', svelte: '^5'},
	peerDependenciesMeta: {'@ryanatkn/moss': {optional: true}, svelte: {optional: true}},
	devDependencies: {
		'@changesets/changelog-git': '^0.2.1',
		'@ryanatkn/belt': '^0.34.1',
		'@ryanatkn/eslint-config': '^0.8.0',
		'@ryanatkn/fuz': '^0.147.0',
		'@ryanatkn/gro': '^0.168.0',
		'@ryanatkn/moss': '^0.36.0',
		'@sveltejs/adapter-static': '^3.0.9',
		'@sveltejs/kit': '^2.37.1',
		'@sveltejs/package': '^2.5.0',
		'@sveltejs/vite-plugin-svelte': '^6.1.4',
		'@types/node': '^24.3.1',
		eslint: '^9.35.0',
		'eslint-plugin-svelte': '^3.12.1',
		'esm-env': '^1.2.2',
		prettier: '^3.6.2',
		'prettier-plugin-svelte': '^3.4.0',
		svelte: '^5.38.7',
		'svelte-check': '^4.3.1',
		tinybench: '^5.0.1',
		tslib: '^2.8.1',
		typescript: '^5.9.2',
		'typescript-eslint': '^8.42.0',
		vitest: '^3.2.4',
	},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [
			{files: 'package.json', options: {useTabs: false}},
			{
				files: ['src/fixtures/generated/**', 'src/lib/samples/sample_*.*'],
				options: {requirePragma: true},
			},
		],
	},
	sideEffects: ['**/*.css'],
	files: ['dist', 'src/lib/**/*.ts', '!src/lib/**/*.test.*', '!dist/**/*.test.*'],
	exports: {
		'./package.json': './package.json',
		'./*.js': {types: './dist/*.d.ts', default: './dist/*.js'},
		'./*.svelte': {
			types: './dist/*.svelte.d.ts',
			svelte: './dist/*.svelte',
			default: './dist/*.svelte',
		},
		'./*.json': {types: './dist/*.json.d.ts', default: './dist/*.json'},
		'./*.css': {default: './dist/*.css'},
	},
} as any;

export const src_json: Src_Json = {
	name: '@ryanatkn/fuz_code',
	version: '0.29.0',
	modules: {
		'./code_sample.js': {
			path: 'code_sample.ts',
			declarations: [
				{name: 'Code_Sample', kind: 'type'},
				{name: 'sample_langs', kind: 'variable'},
				{name: 'Sample_Lang', kind: 'type'},
			],
		},
		'./grammar_clike.js': {
			path: 'grammar_clike.ts',
			declarations: [
				{name: 'class_keywords', kind: 'variable'},
				{name: 'add_grammar_clike', kind: 'function'},
			],
		},
		'./grammar_css.js': {
			path: 'grammar_css.ts',
			declarations: [{name: 'add_grammar_css', kind: 'function'}],
		},
		'./grammar_js.js': {
			path: 'grammar_js.ts',
			declarations: [{name: 'add_grammar_js', kind: 'function'}],
		},
		'./grammar_json.js': {
			path: 'grammar_json.ts',
			declarations: [{name: 'add_grammar_json', kind: 'function'}],
		},
		'./grammar_markdown.js': {
			path: 'grammar_markdown.ts',
			declarations: [{name: 'add_grammar_markdown', kind: 'function'}],
		},
		'./grammar_markup.js': {
			path: 'grammar_markup.ts',
			declarations: [
				{name: 'add_grammar_markup', kind: 'function'},
				{name: 'grammar_markup_add_inlined', kind: 'function'},
				{name: 'grammar_markup_add_attribute', kind: 'function'},
			],
		},
		'./grammar_svelte.js': {
			path: 'grammar_svelte.ts',
			declarations: [
				{name: 'add_grammar_svelte', kind: 'function'},
				{name: 'grammar_svelte_add_inlined', kind: 'function'},
			],
		},
		'./grammar_ts.js': {
			path: 'grammar_ts.ts',
			declarations: [{name: 'add_grammar_ts', kind: 'function'}],
		},
		'./highlight_manager.js': {
			path: 'highlight_manager.ts',
			declarations: [
				{name: 'Highlight_Mode', kind: 'type'},
				{name: 'supports_css_highlight_api', kind: 'function'},
				{name: 'Highlight_Manager', kind: 'class'},
			],
		},
		'./highlight_priorities.gen.js': {
			path: 'highlight_priorities.gen.ts',
			declarations: [{name: 'gen', kind: 'variable'}],
		},
		'./highlight_priorities.js': {
			path: 'highlight_priorities.ts',
			declarations: [
				{name: 'Highlight_Token_Name', kind: 'type'},
				{name: 'highlight_priorities', kind: 'variable'},
			],
		},
		'./syntax_styler_global.js': {
			path: 'syntax_styler_global.ts',
			declarations: [{name: 'syntax_styler_global', kind: 'variable'}],
		},
		'./syntax_styler.js': {
			path: 'syntax_styler.ts',
			declarations: [
				{name: 'Add_Syntax_Grammar', kind: 'type'},
				{name: 'Syntax_Styler', kind: 'class'},
				{name: 'Syntax_Grammar_Value_Raw', kind: 'type'},
				{name: 'Syntax_Grammar_Raw', kind: 'type'},
				{name: 'Syntax_Grammar_Token_Raw', kind: 'type'},
				{name: 'Syntax_Grammar_Token', kind: 'type'},
				{name: 'Syntax_Grammar', kind: 'type'},
				{name: 'Hook_Before_Tokenize_Callback', kind: 'type'},
				{name: 'Hook_After_Tokenize_Callback', kind: 'type'},
				{name: 'Hook_Wrap_Callback', kind: 'type'},
				{name: 'Hook_Before_Tokenize_Callback_Context', kind: 'type'},
				{name: 'Hook_After_Tokenize_Callback_Context', kind: 'type'},
				{name: 'Hook_Wrap_Callback_Context', kind: 'type'},
			],
		},
		'./syntax_token.js': {
			path: 'syntax_token.ts',
			declarations: [
				{name: 'Syntax_Token', kind: 'class'},
				{name: 'Syntax_Token_Stream', kind: 'type'},
			],
		},
		'./tokenize_syntax.js': {
			path: 'tokenize_syntax.ts',
			declarations: [{name: 'tokenize_syntax', kind: 'function'}],
		},
		'./Code_Highlight.svelte': {
			path: 'Code_Highlight.svelte',
			declarations: [{name: 'default', kind: 'component'}],
		},
		'./Code.svelte': {path: 'Code.svelte', declarations: [{name: 'default', kind: 'component'}]},
		'./theme_highlight.css': {
			path: 'theme_highlight.css',
			declarations: [{name: 'default', kind: 'css'}],
		},
		'./theme_variables.css': {
			path: 'theme_variables.css',
			declarations: [{name: 'default', kind: 'css'}],
		},
		'./theme.css': {path: 'theme.css', declarations: [{name: 'default', kind: 'css'}]},
	},
} as any;

// generated by src/routes/package.gen.ts
