// generated by src/routes/package.gen.ts

import type {Package_Json} from '@ryanatkn/gro/package_json.js';
import type {Src_Json} from '@ryanatkn/gro/src_json.js';

export const package_json = {
	name: '@ryanatkn/fuz_code',
	version: '0.21.0',
	description: 'syntax styling utilities and components for TypeScript, Svelte, SvelteKit',
	glyph: '🎨',
	logo: 'logo.svg',
	logo_alt: 'a friendly pink spider facing you',
	public: true,
	license: 'MIT',
	homepage: 'https://code.fuz.dev/',
	repository: 'https://github.com/ryanatkn/fuz_code',
	author: {name: 'Ryan Atkinson', email: 'mail@ryanatkn.com', url: 'https://www.ryanatkn.com/'},
	bugs: 'https://github.com/ryanatkn/fuz_code/issues',
	funding: 'https://www.ryanatkn.com/funding',
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		check: 'gro check',
		test: 'gro test',
		preview: 'vite preview',
		deploy: 'gro deploy',
	},
	type: 'module',
	engines: {node: '>=22.11'},
	peerDependencies: {'@ryanatkn/moss': '*', svelte: '^5'},
	peerDependenciesMeta: {'@ryanatkn/moss': {optional: true}, svelte: {optional: true}},
	devDependencies: {
		'@changesets/changelog-git': '^0.2.1',
		'@ryanatkn/belt': '^0.30.1',
		'@ryanatkn/eslint-config': '^0.8.0',
		'@ryanatkn/fuz': '^0.136.0',
		'@ryanatkn/gro': '^0.150.0',
		'@ryanatkn/moss': '^0.24.3',
		'@sveltejs/adapter-static': '^3.0.8',
		'@sveltejs/kit': '^2.20.5',
		'@sveltejs/package': '^2.3.10',
		'@sveltejs/vite-plugin-svelte': '^5.0.3',
		'@types/node': '^22.14.1',
		eslint: '^9.24.0',
		'eslint-plugin-svelte': '^3.5.1',
		prettier: '^3.5.3',
		'prettier-plugin-svelte': '^3.3.3',
		svelte: '^5.26.2',
		'svelte-check': '^4.1.6',
		tslib: '^2.8.1',
		typescript: '^5.8.3',
		'typescript-eslint': '^8.29.1',
		uvu: '^0.5.6',
	},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	sideEffects: ['**/*.css'],
	files: ['dist', 'src/lib/**/*.ts', '!src/lib/**/*.test.*', '!dist/**/*.test.*'],
	exports: {
		'.': {types: './dist/index.d.ts', default: './dist/index.js'},
		'./package.json': './package.json',
		'./code_sample_inputs.js': {
			types: './dist/code_sample_inputs.d.ts',
			default: './dist/code_sample_inputs.js',
		},
		'./code_sample_outputs.js': {
			types: './dist/code_sample_outputs.d.ts',
			default: './dist/code_sample_outputs.js',
		},
		'./Code.svelte': {
			types: './dist/Code.svelte.d.ts',
			svelte: './dist/Code.svelte',
			default: './dist/Code.svelte',
		},
		'./grammar_clike.js': {types: './dist/grammar_clike.d.ts', default: './dist/grammar_clike.js'},
		'./grammar_css.js': {types: './dist/grammar_css.d.ts', default: './dist/grammar_css.js'},
		'./grammar_js.js': {types: './dist/grammar_js.d.ts', default: './dist/grammar_js.js'},
		'./grammar_json.js': {types: './dist/grammar_json.d.ts', default: './dist/grammar_json.js'},
		'./grammar_markup.js': {
			types: './dist/grammar_markup.d.ts',
			default: './dist/grammar_markup.js',
		},
		'./grammar_svelte.js': {
			types: './dist/grammar_svelte.d.ts',
			default: './dist/grammar_svelte.js',
		},
		'./grammar_ts.js': {types: './dist/grammar_ts.d.ts', default: './dist/grammar_ts.js'},
		'./syntax_styler.js': {types: './dist/syntax_styler.d.ts', default: './dist/syntax_styler.js'},
		'./theme_standalone.css': {default: './dist/theme_standalone.css'},
		'./theme.css': {default: './dist/theme.css'},
	},
} satisfies Package_Json;

export const src_json = {
	name: '@ryanatkn/fuz_code',
	version: '0.21.0',
	modules: {
		'.': {path: 'index.ts', declarations: [{name: 'syntax_styler', kind: 'variable'}]},
		'./package.json': {path: 'package.json', declarations: []},
		'./code_sample_inputs.js': {
			path: 'code_sample_inputs.ts',
			declarations: [
				{name: 'sample_json_code', kind: 'variable'},
				{name: 'sample_html_code', kind: 'variable'},
				{name: 'sample_css_code', kind: 'variable'},
				{name: 'sample_ts_code', kind: 'variable'},
				{name: 'sample_svelte_code', kind: 'variable'},
				{name: 'samples', kind: 'variable'},
			],
		},
		'./code_sample_outputs.js': {
			path: 'code_sample_outputs.ts',
			declarations: [
				{name: 'styled_json_code', kind: 'variable'},
				{name: 'styled_html_code', kind: 'variable'},
				{name: 'styled_css_code', kind: 'variable'},
				{name: 'styled_ts_code', kind: 'variable'},
				{name: 'styled_svelte_code', kind: 'variable'},
			],
		},
		'./Code.svelte': {path: 'Code.svelte', declarations: []},
		'./grammar_clike.js': {
			path: 'grammar_clike.ts',
			declarations: [{name: 'add_grammar_clike', kind: 'variable'}],
		},
		'./grammar_css.js': {
			path: 'grammar_css.ts',
			declarations: [{name: 'add_grammar_css', kind: 'variable'}],
		},
		'./grammar_js.js': {
			path: 'grammar_js.ts',
			declarations: [{name: 'add_grammar_js', kind: 'variable'}],
		},
		'./grammar_json.js': {
			path: 'grammar_json.ts',
			declarations: [{name: 'add_grammar_json', kind: 'variable'}],
		},
		'./grammar_markup.js': {
			path: 'grammar_markup.ts',
			declarations: [
				{name: 'add_grammar_markup', kind: 'variable'},
				{name: 'grammar_markup_add_inlined', kind: 'function'},
				{name: 'grammar_markup_add_attribute', kind: 'function'},
			],
		},
		'./grammar_svelte.js': {
			path: 'grammar_svelte.ts',
			declarations: [
				{name: 'add_grammar_svelte', kind: 'variable'},
				{name: 'grammar_svelte_add_inlined', kind: 'function'},
			],
		},
		'./grammar_ts.js': {
			path: 'grammar_ts.ts',
			declarations: [{name: 'add_grammar_ts', kind: 'variable'}],
		},
		'./syntax_styler.js': {
			path: 'syntax_styler.ts',
			declarations: [
				{name: 'Add_Grammar', kind: 'type'},
				{name: 'Syntax_Styler', kind: 'class'},
				{name: 'Grammar_Value', kind: 'type'},
				{name: 'Grammar', kind: 'type'},
				{name: 'Grammar_Token', kind: 'type'},
				{name: 'tokenize_syntax', kind: 'function'},
				{name: 'Syntax_Token', kind: 'class'},
				{name: 'Syntax_Token_Stream', kind: 'type'},
				{name: 'Hook_Before_Tokenize_Callback', kind: 'type'},
				{name: 'Hook_After_Tokenize_Callback', kind: 'type'},
				{name: 'Hook_Wrap_Callback', kind: 'type'},
				{name: 'Hook_Before_Tokenize_Callback_Context', kind: 'type'},
				{name: 'Hook_After_Tokenize_Callback_Context', kind: 'type'},
				{name: 'Hook_Wrap_Callback_Context', kind: 'type'},
			],
		},
		'./theme_standalone.css': {path: 'theme_standalone.css', declarations: []},
		'./theme.css': {path: 'theme.css', declarations: []},
	},
} satisfies Src_Json;

// generated by src/routes/package.gen.ts
