// generated by src/routes/package.gen.ts

import type {Package_Json} from '@ryanatkn/gro/package_json.js';
import type {Src_Json} from '@ryanatkn/gro/src_json.js';

export const package_json = {
	name: '@ryanatkn/fuz_code',
	description: 'syntax highlighting using prismjs for Svelte, SvelteKit, TypeScript, and Fuz',
	version: '0.12.0',
	public: true,
	license: 'MIT',
	type: 'module',
	homepage: 'https://code.fuz.dev/',
	repository: 'https://github.com/ryanatkn/fuz_code',
	author: {name: 'Ryan Atkinson', email: 'mail@ryanatkn.com', url: 'https://www.ryanatkn.com/'},
	bugs: 'https://github.com/ryanatkn/fuz_code/issues',
	funding: 'https://www.ryanatkn.com/funding',
	engines: {node: '>=20.10'},
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		test: 'gro test',
		deploy: 'gro deploy',
	},
	files: ['dist'],
	peerDependencies: {'prism-svelte': '^0.5', prismjs: '^1', svelte: '^5.0.0-next.0'},
	devDependencies: {
		'@changesets/changelog-git': '^0.2.0',
		'@ryanatkn/belt': '^0.20.10',
		'@ryanatkn/eslint-config': '^0.1.2',
		'@ryanatkn/fuz': '^0.102.0',
		'@ryanatkn/gro': '^0.116.2',
		'@ryanatkn/moss': '^0.3.0',
		'@sveltejs/adapter-static': '^3.0.1',
		'@sveltejs/kit': '^2.5.10',
		'@sveltejs/package': '^2.3.1',
		'@sveltejs/vite-plugin-svelte': '^3.1.1',
		'@types/prismjs': '^1.26.4',
		'@typescript-eslint/eslint-plugin': '^7.13.0',
		'@typescript-eslint/parser': '^7.13.0',
		eslint: '^8.57.0',
		'eslint-plugin-svelte': '^2.39.3',
		prettier: '^3.3.2',
		'prettier-plugin-svelte': '^3.2.4',
		'prism-svelte': '^0.5.0',
		prismjs: '^1.29.0',
		svelte: '^5.0.0-next.153',
		'svelte-check': '^3.8.0',
		tslib: '^2.6.3',
		typescript: '^5.4.5',
		uvu: '^0.5.6',
	},
	eslintConfig: {root: true, extends: '@ryanatkn'},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	exports: {
		'./package.json': './package.json',
		'./Code.svelte': {
			svelte: './dist/Code.svelte',
			default: './dist/Code.svelte',
			types: './dist/Code.svelte.d.ts',
		},
		'./prism.css': {default: './dist/prism.css'},
		'./remove_prism_css_vite_plugin.js': {
			default: './dist/remove_prism_css_vite_plugin.js',
			types: './dist/remove_prism_css_vite_plugin.d.ts',
		},
	},
} satisfies Package_Json;

export const src_json = {
	name: '@ryanatkn/fuz_code',
	version: '0.12.0',
	modules: {
		'./package.json': {path: 'package.json', declarations: []},
		'./Code.svelte': {path: 'Code.svelte', declarations: []},
		'./prism.css': {path: 'prism.css', declarations: []},
		'./remove_prism_css_vite_plugin.js': {
			path: 'remove_prism_css_vite_plugin.ts',
			declarations: [{name: 'remove_prism_css', kind: 'function'}],
		},
	},
} satisfies Src_Json;

// generated by src/routes/package.gen.ts
